steps:
  verify:
    image: node:22-bookworm-slim
    commands:
      - npm ci
      - npm run build
    when:
      event:
        - push
        - pull_request
        - tag

  publish-main:
    image: woodpeckerci/plugin-kaniko
    depends_on:
      - verify
    settings:
      registry: rg.furkantrn.com
      repo: rg.furkantrn.com/movie-archive
      dockerfile: Dockerfile
      context: .
      cache: true
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      username:
        from_secret: rg_username
      password:
        from_secret: rg_password
    when:
      branch:
        - main
        - master
      event:
        - push

  publish-tag:
    image: woodpeckerci/plugin-kaniko
    depends_on:
      - verify
    settings:
      registry: rg.furkantrn.com
      repo: rg.furkantrn.com/movie-archive
      dockerfile: Dockerfile
      context: .
      cache: true
      auto_tag: true
      username:
        from_secret: rg_username
      password:
        from_secret: rg_password
    when:
      event:
        - tag
